/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0284c7',
          600: '#0369a1',
          700: '#075985',
          800: '#0c4a6e',
          900: '#082f49',
          950: '#041727',
        },
        semantic: {
          text: 'var(--text)',
          'text-muted': 'var(--text-muted)',
          'text-subtle': 'var(--text-subtle)',
          border: 'var(--border)',
          'border-strong': 'var(--border-strong)',
          surface: 'var(--surface)',
          'surface-muted': 'var(--surface-muted)',
          'surface-subtle': 'var(--surface-subtle)',
          canvas: 'var(--canvas)',
          accent: 'var(--accent)',
          'accent-hover': 'var(--accent-hover)',
          'accent-soft': 'var(--accent-soft)',
          'accent-ring': 'var(--accent-ring)',
          success: 'var(--success)',
          'success-soft': 'var(--success-soft)',
          'success-ring': 'var(--success-ring)',
          warning: 'var(--warning)',
          'warning-soft': 'var(--warning-soft)',
          'warning-ring': 'var(--warning-ring)',
          danger: 'var(--danger)',
          'danger-soft': 'var(--danger-soft)',
          'danger-ring': 'var(--danger-ring)',
          info: 'var(--info)',
          'info-soft': 'var(--info-soft)',
          'info-ring': 'var(--info-ring)',
        },
      },
      borderRadius: {
        'ui-sm': 'var(--radius-sm)',
        'ui-md': 'var(--radius-md)',
        'ui-lg': 'var(--radius-lg)',
        'ui-xl': 'var(--radius-xl)',
        'ui-2xl': 'var(--radius-2xl)',
      },
      boxShadow: {
        'ui-sm': 'var(--shadow-sm)',
        'ui-md': 'var(--shadow-md)',
        'ui-lg': 'var(--shadow-lg)',
        'ui-xl': 'var(--shadow-xl)',
      },
      fontFamily: {
        sans: ['DM Sans', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Manrope', 'DM Sans', 'sans-serif'],
      },
      transitionDuration: {
        DEFAULT: '180ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
}
