import { useCallback, useEffect, useState } from 'react';
import { apiRequest } from '../lib/api';
import { useAuth } from '../context/AuthContext';

type Project = { id: string; name: string; status: string; budget_minutes: number; budget_amount_cents: number; currency: string };
type Task = { id: string; project_id: string; title: string; status: string; estimate_minutes: number };
type Employee = { id: string; full_name: string; email?: string; title?: string; billing_rate_cents: number; cost_rate_cents: number; is_active: boolean };
type Entry = { id: string; project_id: string; entry_date: string; minutes: number; description: string; is_billable: boolean; approval_status: string };
type LeaveRequest = { id: string; employee_id: string; start_date: string; end_date: string; status: string; reason?: string };
type Invoice = { id: string; invoice_number: string; client_name: string; status: string; currency: string; total_cents: number; paid_cents: number; issue_date: string; due_date: string; line_items: { id: string; description: string; amount_cents: number }[] };
type Expense = { id: string; vendor: string; category: string; description: string; amount_cents: number; currency: string; expense_date: string; status: string };
type ApprovalItem = { id: string; entity_type: string; label: string; amount_cents?: number; currency?: string; created_at: string };
type MigrationJob = { id: string; filename: string; target: string; status: string; row_count?: number; imported?: number; errors?: string[]; sample?: Record<string, string>[] };
type Document = { id: string; title: string; category: string; content: string; updated_at: string };
type WorkflowRun = { id: string; workflow_type: string; status: string; created_at: string; result_data: { items?: Record<string, unknown>[] } };
const input = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-sky-500';
const button = 'rounded-lg bg-sky-600 px-4 py-2 text-sm font-semibold text-white hover:bg-sky-500 disabled:opacity-50';
const shell = 'mx-auto max-w-7xl space-y-5';

export function ProjectsPage() {
  const [rows, setRows] = useState<Project[]>([]); const [tasks, setTasks] = useState<Record<string, Task[]>>({}); const [expanded, setExpanded] = useState('');
  const [name, setName] = useState(''); const [budgetHours, setBudgetHours] = useState(''); const [budget, setBudget] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setRows(await apiRequest<Project[]>('/operations/projects')); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load projects'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const addProject = async (e: React.FormEvent) => { e.preventDefault(); try { await apiRequest('/operations/projects', { method: 'POST', body: JSON.stringify({ name, budget_minutes: Math.round(Number(budgetHours || 0) * 60), budget_amount_cents: Math.round(Number(budget || 0) * 100) }) }); setName(''); setBudgetHours(''); setBudget(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save project'); } };
  const toggle = async (project: Project) => { if (expanded === project.id) { setExpanded(''); return; } setExpanded(project.id); try { const result = await apiRequest<Task[]>(`/operations/projects/${project.id}/tasks`); setTasks((old) => ({ ...old, [project.id]: result })); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load tasks'); } };
  const addTask = async (projectId: string, title: string) => { try { await apiRequest(`/operations/projects/${projectId}/tasks`, { method: 'POST', body: JSON.stringify({ title }) }); const updated = await apiRequest<Task[]>(`/operations/projects/${projectId}/tasks`); setTasks((old) => ({ ...old, [projectId]: updated })); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to add task'); } };
  const changeTaskStatus = async (task: Task, status: string) => { try { await apiRequest(`/operations/tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); setTasks((old) => ({ ...old, [task.project_id]: old[task.project_id]?.map((row) => row.id === task.id ? { ...row, status } : row) || [] })); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update task'); } };
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">Projects & Tasks</h1><p className="mt-1 text-sm text-slate-500">Track delivery, task estimates, and budget burn.</p></header>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<form onSubmit={(e) => void addProject(e)} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-[2fr_1fr_1fr_auto]"><input className={input} required placeholder="Project name" value={name} onChange={(e) => setName(e.target.value)} /><input className={input} type="number" min="0" placeholder="Hour budget" value={budgetHours} onChange={(e) => setBudgetHours(e.target.value)} /><input className={input} type="number" min="0" step="0.01" placeholder="Amount budget (USD)" value={budget} onChange={(e) => setBudget(e.target.value)} /><button className={button}>Create project</button></form><div className="space-y-3">{rows.map((project) => <section key={project.id} className="rounded-xl border border-slate-200 bg-white"><button className="flex w-full items-center justify-between px-5 py-4 text-left" onClick={() => void toggle(project)}><span><strong className="text-slate-900">{project.name}</strong><span className="ml-3 text-xs text-slate-500">{project.status}</span></span><span className="text-sm text-slate-500">{(project.budget_minutes / 60).toFixed(1)}h · {project.currency} {(project.budget_amount_cents / 100).toFixed(2)} budget</span></button>{expanded === project.id && <div className="border-t border-slate-100 p-4"><ul className="mb-3 space-y-2">{(tasks[project.id] || []).map((task) => <li key={task.id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{task.title}</span><select aria-label={`Status for ${task.title}`} className="rounded border border-slate-200 bg-white px-2 py-1" value={task.status} onChange={(e) => void changeTaskStatus(task, e.target.value)}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="done">Done</option></select></li>)}</ul><form className="flex gap-2" onSubmit={(e) => { e.preventDefault(); const form = e.currentTarget; const title = new FormData(form).get('title')?.toString() || ''; if (title) void addTask(project.id, title); form.reset(); }}><input name="title" required className={input} placeholder="Add a task" /><button className={button}>Add task</button></form></div>}</section>)}{!rows.length && <p className="rounded-xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">No projects yet.</p>}</div></div>;
}

export function TimesheetsPage() {
  const [entries, setEntries] = useState<Entry[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [hours, setHours] = useState(''); const [description, setDescription] = useState(''); const [billable, setBillable] = useState(true); const [error, setError] = useState('');
  const { user } = useAuth(); const canApprove = ['owner', 'approver', 'project_manager', 'finance'].includes(user?.role || '');
  const load = useCallback(async () => { try { const [e, p] = await Promise.all([apiRequest<Entry[]>('/operations/timesheets'), apiRequest<Project[]>('/operations/projects')]); setEntries(e); setProjects(p); if (!projectId && p[0]) setProjectId(p[0].id); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load timesheets'); } }, [projectId]);
  useEffect(() => { void load(); }, [load]);
  const add = async (e: React.FormEvent) => { e.preventDefault(); try { await apiRequest('/operations/timesheets', { method: 'POST', body: JSON.stringify({ project_id: projectId, entry_date: date, minutes: Math.round(Number(hours) * 60), description, is_billable: billable }) }); setHours(''); setDescription(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save time'); } };
  const decide = async (id: string, status: string) => { try { await apiRequest(`/operations/timesheets/${id}/approval`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update approval'); } };
  const projectName = (id: string) => projects.find((p) => p.id === id)?.name || 'Project';
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">Timesheets</h1><p className="mt-1 text-sm text-slate-500">Log project time and review pending entries.</p></header>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<form onSubmit={(e) => void add(e)} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_1fr_1fr_2fr_auto]"><select className={input} required value={projectId} onChange={(e) => setProjectId(e.target.value)}>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input className={input} type="date" required value={date} onChange={(e) => setDate(e.target.value)} /><input className={input} type="number" required min="0.1" max="24" step="0.1" placeholder="Hours" value={hours} onChange={(e) => setHours(e.target.value)} /><input className={input} required placeholder="Work description" value={description} onChange={(e) => setDescription(e.target.value)} /><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={billable} onChange={(e) => setBillable(e.target.checked)} />Billable</label><button className={button} disabled={!projects.length}>Log time</button></form><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Project</th><th className="px-4 py-3">Work</th><th className="px-4 py-3">Hours</th><th className="px-4 py-3">Billable</th><th className="px-4 py-3">Approval</th>{canApprove && <th className="px-4 py-3">Actions</th>}</tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className="border-t border-slate-100"><td className="px-4 py-3">{entry.entry_date}</td><td className="px-4 py-3">{projectName(entry.project_id)}</td><td className="px-4 py-3">{entry.description}</td><td className="px-4 py-3">{(entry.minutes / 60).toFixed(1)}</td><td className="px-4 py-3">{entry.is_billable ? 'Yes' : 'No'}</td><td className="px-4 py-3 capitalize">{entry.approval_status}</td>{canApprove && <td className="space-x-2 px-4 py-3">{entry.approval_status === 'pending' && <><button className="font-semibold text-emerald-700" onClick={() => void decide(entry.id, 'approved')}>Approve</button><button className="font-semibold text-rose-600" onClick={() => void decide(entry.id, 'rejected')}>Reject</button></>}</td>}</tr>)}</tbody></table>{!entries.length && <p className="p-8 text-center text-sm text-slate-500">No time entries yet.</p>}</div></div>;
}

export function PeoplePage() {
  const [rows, setRows] = useState<Employee[]>([]); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [title, setTitle] = useState(''); const [billing, setBilling] = useState(''); const [cost, setCost] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setRows(await apiRequest<Employee[]>('/operations/people')); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load team'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const add = async (e: React.FormEvent) => { e.preventDefault(); try { await apiRequest('/operations/people', { method: 'POST', body: JSON.stringify({ full_name: name, email: email || null, title: title || null, billing_rate_cents: Math.round(Number(billing || 0) * 100), cost_rate_cents: Math.round(Number(cost || 0) * 100) }) }); setName(''); setEmail(''); setTitle(''); setBilling(''); setCost(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to add teammate'); } };
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">People & Team</h1><p className="mt-1 text-sm text-slate-500">Maintain employee records, rates, and leave requests.</p></header>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<form onSubmit={(e) => void add(e)} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-6"><input className={input} required placeholder="Full name" value={name} onChange={(e) => setName(e.target.value)} /><input className={input} type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} /><input className={input} placeholder="Role or title" value={title} onChange={(e) => setTitle(e.target.value)} /><input className={input} type="number" min="0" step="0.01" placeholder="Billing rate/hour" value={billing} onChange={(e) => setBilling(e.target.value)} /><input className={input} type="number" min="0" step="0.01" placeholder="Cost rate/hour" value={cost} onChange={(e) => setCost(e.target.value)} /><button className={button}>Add teammate</button></form><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Title</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Bill rate</th><th className="px-4 py-3">Cost rate</th></tr></thead><tbody>{rows.map((person) => <tr key={person.id} className="border-t border-slate-100"><td className="px-4 py-3 font-medium">{person.full_name}</td><td className="px-4 py-3">{person.title || '—'}</td><td className="px-4 py-3">{person.email || '—'}</td><td className="px-4 py-3">${(person.billing_rate_cents / 100).toFixed(2)}</td><td className="px-4 py-3">${(person.cost_rate_cents / 100).toFixed(2)}</td></tr>)}</tbody></table>{!rows.length && <p className="p-8 text-center text-sm text-slate-500">No team members added.</p>}</div><LeaveWidget employees={rows} /></div>;
}

function LeaveWidget({ employees }: { employees: Employee[] }) {
  const [items, setItems] = useState<LeaveRequest[]>([]); const [employeeId, setEmployeeId] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setItems(await apiRequest<LeaveRequest[]>('/operations/leave-requests')); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load leave requests'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const add = async (e: React.FormEvent) => { e.preventDefault(); try { await apiRequest('/operations/leave-requests', { method: 'POST', body: JSON.stringify({ employee_id: employeeId, start_date: start, end_date: end, reason: reason || null }) }); setStart(''); setEnd(''); setReason(''); setError(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to submit leave request'); } };
  return <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><div><h2 className="font-bold text-slate-900">Leave requests</h2><p className="mt-1 text-xs text-slate-500">Record time away against an employee.</p></div>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<form onSubmit={(e) => void add(e)} className="grid gap-2 sm:grid-cols-[1fr_1fr_1fr_2fr_auto]"><select className={input} required value={employeeId} onChange={(e) => setEmployeeId(e.target.value)}><option value="">Select employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name}</option>)}</select><input className={input} type="date" required value={start} onChange={(e) => setStart(e.target.value)} /><input className={input} type="date" required value={end} onChange={(e) => setEnd(e.target.value)} /><input className={input} placeholder="Reason (optional)" value={reason} onChange={(e) => setReason(e.target.value)} /><button className={button} disabled={!employees.length}>Submit request</button></form><ul className="divide-y divide-slate-100">{items.map((item) => <li key={item.id} className="flex justify-between py-2 text-sm"><span>{employees.find((employee) => employee.id === item.employee_id)?.full_name || 'Team member'} · {item.start_date} to {item.end_date}</span><span className="capitalize text-slate-500">{item.status}</span></li>)}</ul></section>;
}

export function InvoicingPage() {
  const [invoices, setInvoices] = useState<Invoice[]>([]); const [client, setClient] = useState(''); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [tax, setTax] = useState('0'); const [issueDate, setIssueDate] = useState(new Date().toISOString().slice(0, 10)); const [dueDate, setDueDate] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setInvoices(await apiRequest<Invoice[]>('/billing/invoices')); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load invoices'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { await apiRequest('/billing/invoices', { method: 'POST', body: JSON.stringify({ client_name: client, currency: 'USD', issue_date: issueDate, due_date: dueDate, tax_bps: Math.round(Number(tax) * 100), line_items: [{ description, quantity: 1, unit_price_cents: Math.round(Number(amount) * 100) }] }) }); setClient(''); setDescription(''); setAmount(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create invoice'); } };
  const pay = async (invoice: Invoice) => { const remaining = invoice.total_cents - invoice.paid_cents; if (remaining <= 0) return; try { await apiRequest(`/billing/invoices/${invoice.id}/payments`, { method: 'POST', body: JSON.stringify({ amount_cents: remaining, paid_date: new Date().toISOString().slice(0, 10), method: 'other' }) }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to record payment'); } };
  const send = async (invoice: Invoice) => { try { await apiRequest(`/billing/invoices/${invoice.id}/status`, { method: 'PATCH', body: JSON.stringify({ status: 'sent' }) }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to mark invoice sent'); } };
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">Invoices & Payments</h1><p className="mt-1 text-sm text-slate-500">Create invoices, record payments, and track balances.</p></header>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<form onSubmit={(e) => void create(e)} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-3"><input className={input} required placeholder="Client name" value={client} onChange={(e) => setClient(e.target.value)} /><input className={input} required placeholder="Line item" value={description} onChange={(e) => setDescription(e.target.value)} /><input className={input} required type="number" min="0.01" step="0.01" placeholder="Amount (USD)" value={amount} onChange={(e) => setAmount(e.target.value)} /><label className="text-xs text-slate-500">Issue date<input className={`${input} mt-1`} type="date" required value={issueDate} onChange={(e) => setIssueDate(e.target.value)} /></label><label className="text-xs text-slate-500">Due date<input className={`${input} mt-1`} type="date" required value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label><div className="flex gap-2"><input className={input} type="number" min="0" max="100" step="0.01" placeholder="Tax %" value={tax} onChange={(e) => setTax(e.target.value)} /><button className={button}>Create draft</button></div></form><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Invoice</th><th className="px-4 py-3">Client</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Balance</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">{invoice.invoice_number}</td><td className="px-4 py-3">{invoice.client_name}</td><td className="px-4 py-3">{invoice.due_date}</td><td className="px-4 py-3">{invoice.currency} {(invoice.total_cents / 100).toFixed(2)}</td><td className="px-4 py-3">{invoice.currency} {((invoice.total_cents - invoice.paid_cents) / 100).toFixed(2)}</td><td className="px-4 py-3 capitalize">{invoice.status}</td><td className="space-x-2 px-4 py-3">{invoice.status === 'draft' && <button onClick={() => void send(invoice)} className="font-semibold text-sky-700">Mark sent</button>}{invoice.status !== 'paid' && invoice.status !== 'void' && <button onClick={() => void pay(invoice)} className="font-semibold text-emerald-700">Record payment</button>}</td></tr>)}</tbody></table>{!invoices.length && <p className="p-8 text-center text-sm text-slate-500">No invoices yet.</p>}</div></div>;
}

export function ExpensesPage() {
  const [expenses, setExpenses] = useState<Expense[]>([]); const [vendor, setVendor] = useState(''); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [error, setError] = useState(''); const { user } = useAuth();
  const canReview = ['owner', 'finance', 'approver'].includes(user?.role || '');
  const load = useCallback(async () => { try { setExpenses(await apiRequest<Expense[]>('/billing/expenses')); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load expenses'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { await apiRequest('/billing/expenses', { method: 'POST', body: JSON.stringify({ vendor, description, amount_cents: Math.round(Number(amount) * 100), expense_date: date, currency: 'USD' }) }); setVendor(''); setDescription(''); setAmount(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to submit expense'); } };
  const review = async (expense: Expense, status: string) => { try { await apiRequest(`/billing/expenses/${expense.id}/review`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to review expense'); } };
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">Expenses & Vendor Bills</h1><p className="mt-1 text-sm text-slate-500">Submit an expense and route it for finance review.</p></header>{error && <p role="alert" className="break-all text-sm text-rose-700">{error}</p>}<form onSubmit={(e) => void create(e)} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_2fr_1fr_1fr_auto]"><input className={input} required placeholder="Vendor" value={vendor} onChange={(e) => setVendor(e.target.value)} /><input className={input} required placeholder="Description" value={description} onChange={(e) => setDescription(e.target.value)} /><input className={input} required type="number" min="0.01" step="0.01" placeholder="Amount (USD)" value={amount} onChange={(e) => setAmount(e.target.value)} /><input className={input} required type="date" value={date} onChange={(e) => setDate(e.target.value)} /><button className={button}>Submit</button></form><div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Vendor</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th>{canReview && <th className="px-4 py-3">Review</th>}</tr></thead><tbody>{expenses.map((expense) => <tr key={expense.id} className="border-t border-slate-100"><td className="px-4 py-3">{expense.expense_date}</td><td className="px-4 py-3 font-medium">{expense.vendor}</td><td className="px-4 py-3">{expense.description}</td><td className="px-4 py-3">{expense.currency} {(expense.amount_cents / 100).toFixed(2)}</td><td className="px-4 py-3 capitalize">{expense.status}</td>{canReview && <td className="space-x-2 px-4 py-3">{expense.status === 'pending' && <><button className="font-semibold text-emerald-700" onClick={() => void review(expense, 'approved')}>Approve</button><button className="font-semibold text-rose-600" onClick={() => void review(expense, 'rejected')}>Reject</button></>}</td>}</tr>)}</tbody></table>{!expenses.length && <p className="p-8 text-center text-sm text-slate-500">No expenses submitted.</p>}</div></div>;
}

export function MigrationPage() {
  const [jobs, setJobs] = useState<MigrationJob[]>([]); const [target, setTarget] = useState('leads'); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<MigrationJob | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setJobs(await apiRequest<MigrationJob[]>('/migration/jobs')); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load imports'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const runDry = async (e: React.FormEvent) => { e.preventDefault(); if (!file) return; setBusy(true); setError(''); const form = new FormData(); form.append('target', target); form.append('file', file); try { setPreview(await apiRequest<MigrationJob>('/migration/dry-run', { method: 'POST', body: form })); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to preview import'); } finally { setBusy(false); } };
  const apply = async () => { if (!preview) return; setBusy(true); try { const done = await apiRequest<MigrationJob>(`/migration/jobs/${preview.id}/apply`, { method: 'POST' }); setPreview({ ...preview, ...done }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to apply import'); } finally { setBusy(false); } };
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">Odoo Migration Center</h1><p className="mt-1 text-sm text-slate-500">Import CSV exports with a validation preview before writing records.</p></header>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<form onSubmit={(e) => void runDry(e)} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-5 sm:grid-cols-[1fr_2fr_auto]"><select className={input} value={target} onChange={(e) => setTarget(e.target.value)}><option value="leads">Leads</option><option value="companies">Companies</option><option value="contacts">Contacts</option></select><input className={input} required type="file" accept=".csv,text/csv" onChange={(e) => setFile(e.target.files?.[0] || null)} /><button className={button} disabled={busy || !file}>{busy ? 'Checking…' : 'Dry run CSV'}</button></form>{preview && <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Preview: {preview.filename} ({preview.row_count || preview.imported || 0} rows)</h2>{preview.status === 'dry_run' && <button disabled={busy || Boolean(preview.errors?.length)} className={button} onClick={() => void apply()}>Apply import</button>}</div>{preview.errors?.map((item) => <p key={item} className="text-sm text-rose-700">{item}</p>)}{preview.status === 'completed' && <p className="text-sm text-emerald-700">Imported {preview.imported} records.</p>}<pre className="max-h-72 overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(preview.sample || [], null, 2)}</pre></section>}<section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-3 font-bold">Import history</h2><ul className="divide-y divide-slate-100">{jobs.map((job) => <li key={job.id} className="flex justify-between py-3 text-sm"><span>{job.filename} · {job.target}</span><span className="capitalize text-slate-500">{job.status}</span></li>)}</ul>{!jobs.length && <p className="text-sm text-slate-500">No migration runs yet.</p>}</section></div>;
}

export function DocumentsPage() {
  const [documents, setDocuments] = useState<Document[]>([]); const [query, setQuery] = useState(''); const [title, setTitle] = useState(''); const [category, setCategory] = useState('general'); const [content, setContent] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async (q = query) => { try { setDocuments(await apiRequest<Document[]>(`/documents${q ? `?q=${encodeURIComponent(q)}` : ''}`)); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load documents'); } }, [query]);
  useEffect(() => { void load(''); }, []);
  const save = async (e: React.FormEvent) => { e.preventDefault(); try { await apiRequest('/documents', { method: 'POST', body: JSON.stringify({ title, category, content }) }); setTitle(''); setContent(''); await load(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save document'); } };
  const remove = async (id: string) => { try { await apiRequest(`/documents/${id}`, { method: 'DELETE' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete document'); } };
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">Documents & SOWs</h1><p className="mt-1 text-sm text-slate-500">Save contracts, statements of work, and notes for searchable team knowledge.</p></header>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<form onSubmit={(e) => void save(e)} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-5"><div className="grid gap-2 sm:grid-cols-2"><input className={input} required placeholder="Document title" value={title} onChange={(e) => setTitle(e.target.value)} /><select className={input} value={category} onChange={(e) => setCategory(e.target.value)}><option value="general">General</option><option value="contract">Contract</option><option value="sow">Statement of work</option><option value="policy">Policy</option><option value="rate_card">Rate card</option></select></div><textarea className={input} required rows={4} placeholder="Paste document text" value={content} onChange={(e) => setContent(e.target.value)} /><button className={`${button} justify-self-end`}>Save document</button></form><form className="flex gap-2" onSubmit={(e) => { e.preventDefault(); void load(); }}><input className={input} placeholder="Search title or document text" value={query} onChange={(e) => setQuery(e.target.value)} /><button className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Search</button></form><div className="space-y-3">{documents.map((doc) => <article key={doc.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-3"><div><h2 className="font-bold text-slate-900">{doc.title}</h2><p className="mt-1 text-xs uppercase text-slate-500">{doc.category}</p></div><button className="text-sm font-semibold text-rose-600" onClick={() => void remove(doc.id)}>Delete</button></div><p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{doc.content}</p></article>)}{!documents.length && <p className="rounded-xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">No matching documents.</p>}</div></div>;
}

export function WorkflowsPage() {
  const [runs, setRuns] = useState<WorkflowRun[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setRuns(await apiRequest<WorkflowRun[]>('/workflows')); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load workflows'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const run = async (type: string) => { setBusy(true); setError(''); try { await apiRequest(`/workflows/${type}`, { method: 'POST' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to run workflow'); } finally { setBusy(false); } };
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">Agent Workflows</h1><p className="mt-1 text-sm text-slate-500">Run deterministic lead, project, and invoice checks. Each run saves its results for review.</p></header>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-3">{[['lead_qualification', 'Qualify open leads'], ['project_health', 'Review project health'], ['invoice_aging', 'Check invoice aging']].map(([type, label]) => <button key={type} disabled={busy} onClick={() => void run(type)} className="rounded-xl border border-slate-200 bg-white p-5 text-left font-semibold text-slate-800 hover:border-sky-300 disabled:opacity-50">{label}<span className="mt-2 block text-xs font-normal text-slate-500">Run check</span></button>)}</div><div className="space-y-3">{runs.map((item) => <details key={item.id} className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer font-semibold text-slate-900">{item.workflow_type.replaceAll('_', ' ')} · {new Date(item.created_at).toLocaleString()} · {item.result_data.items?.length || 0} results</summary><pre className="mt-3 max-h-80 overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(item.result_data.items || [], null, 2)}</pre></details>)}{!runs.length && <p className="rounded-xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">No workflow runs yet.</p>}</div></div>;
}

export function ApprovalsPage() {
  const [items, setItems] = useState<ApprovalItem[]>([]); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setItems(await apiRequest<ApprovalItem[]>('/workflows/approvals')); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load approvals'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const decide = async (item: ApprovalItem, decision: string) => { try { await apiRequest(`/workflows/approvals/${item.entity_type}/${item.id}`, { method: 'POST', body: JSON.stringify({ decision }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update approval'); } };
  return <div className={shell}><header><h1 className="text-2xl font-bold text-slate-900">Approvals Inbox</h1><p className="mt-1 text-sm text-slate-500">Review submitted time entries and expenses that need a decision.</p></header>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<div className="divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white">{items.map((item) => <article key={`${item.entity_type}-${item.id}`} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><span className="rounded bg-amber-100 px-2 py-1 text-xs font-semibold uppercase text-amber-800">{item.entity_type}</span><p className="mt-2 font-medium text-slate-900">{item.label}</p>{item.amount_cents != null && <p className="text-sm text-slate-500">{item.currency} {(item.amount_cents / 100).toFixed(2)}</p>}</div><div className="flex gap-3"><button onClick={() => void decide(item, 'approved')} className="font-semibold text-emerald-700">Approve</button><button onClick={() => void decide(item, 'rejected')} className="font-semibold text-rose-600">Reject</button></div></article>)}{!items.length && <p className="p-8 text-center text-sm text-slate-500">Nothing needs approval.</p>}</div></div>;
}
